### ISSUE TITLE
05.TheMonotonyOfExcellence.md broken link

### ISSUE THREAD

**Issue by laurenlucero** [SpiffInc/engineers_field_guide#2]
The link attached to the text "lottery winners and people who become quadriplegic" is broken - 404 Not Found

**Comment by jessegilbride** [comment]
One of these might be a close match to what they were going for: 

https://duckduckgo.com/?q=%22lottery+winners%22+%22quadriplegic%22

**Comment by mmmries** [comment]
Fixed this in 718ffd3d61b0348730ee17f569af1136d73bd490

Thanks for pointing it out ❤️ 💛 💙 💚 💜
